---
title: "Where's George Data"
author: "Nathan Williamson"
date: "September 18, 2017"
output: html_document
---

Get Data first...
```{r}
setwd("C:/Users/Nate/Desktop/wheresgeorge")
fulldata <- read.csv("WG_ChicagoTrajectories_5.1.17.csv", header=TRUE)
attach(fulldata)
fulldata$Kilometers <- ((fulldata$Kilometers)/1000)
#head(fulldata)
```

Sort data method 1: 
We use the time value of the data point for delta t
```{r}
deltatd1 <- data.frame()
 n <- numeric(1)
 n <- 1
 lengthdata <- nrow(fulldata)-1
   for (i in 1:lengthdata)
     {
         if (fulldata[i+1,1] == fulldata[i,1]) 
              {
                 deltatd1[n,1] <- fulldata[i+1,3] 
                 deltatd1[n,2] <- (fulldata[i+1,4])^2
                 deltatd1[n,3] <- fulldata[i+1,4]
                 n <- n+1
             }
       
   }
attach(deltatd1)
names(deltatd1) <- c("t","dsq","d")
head(deltatd1)
```

Now we can plot different subsets of the data...
```{r, warning=FALSE, message=FALSE}
#make a new dataframe by subsetting time and distance
time <- 300
distance <- 300
tdlim <- data.frame()
   tdlim <- subset(deltatd1, d<distance & t<time, select = c(t,dsq,d))
   names(tdlim) <- c("t", "dsq", "d")
   attach(tdlim)
   head(tdlim)
   #plot the data
   limdata <- aggregate(x=tdlim$dsq, by=list(tdlim$t), FUN=mean)
   names(limdata) <- c("t", "xsq")
   attach(limdata)
   plot(limdata$t, limdata$xsq, pch=16, cex=1.3, col="blue", main="Distance^2 vs. Time", 
        xlab="Time(days)", ylab="Distance^2 (km^2)")
   abline(lm(xsq ~t))
   fit <- lm(xsq ~ t)
   summary(fit)
   
   
```




Sort data method 2:
We use the difference between the time values for delta t
```{r}
deltatd2 <- data.frame()
 n <- numeric(1)
 n <- 1
 lengthdata <- nrow(fulldata)-1
   for (i in 1:lengthdata)
     {
         if (fulldata[i+1,1] == fulldata[i,1]) 
              {
                 deltatd2[n,1] <- abs(fulldata[i+1,3] - fulldata[i,3])
                 deltatd2[n,2] <- (fulldata[i+1,4] - fulldata[i,4])^2
                 deltatd2[n,3] <- abs(fulldata[i+1,4] - fulldata[i,4])
                 n <- n+1
             }
       
   }
attach(deltatd2)
names(deltatd2) <- c("t","dsq","d")
head(deltatd2)
```



Now we can plot different subsets of the data...
```{r, warning=FALSE, message=FALSE}
#make a new dataframe by subsetting time and distance
time <- 300
distance <- 300
tdlim <- data.frame()
   tdlim <- subset(deltatd2, d<distance & t<time, select = c(t,dsq,d))
   names(tdlim) <- c("t", "dsq", "d")
   attach(tdlim)
   head(tdlim)
   #plot the data
   limdata <- aggregate(x=tdlim$dsq, by=list(tdlim$t), FUN=mean)
   names(limdata) <- c("t", "xsq")
   attach(limdata)
   plot(limdata$t, limdata$xsq, pch=16, cex=1.3, col="blue", main="Distance^2 vs. Time", 
        xlab="Time(days)", ylab="Distance^2 (km^2)")
   abline(lm(xsq ~t))
   fit <- lm(xsq ~ t)
   summary(fit)
   
   
```

